version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running Astro build..."
      - npm run build
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
