version: 0.2

phases:
  install:
    runtime-versions:
      # This tells CodeBuild to use the latest Node.js 20, which meets the requirement.
      # You could also use '18' to get the latest 18.x version.
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running build..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Or 'build', depending on your project's output folder
