version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running Astro build..."
      - "npm run build 2>&1 | tee build.log"
      - "echo Build exit code: $?"
      - "echo Build log contents:"
      - cat build.log
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
