version: 0.2

phases:
  pre_build:
    commands:
      - echo "Using Docker to run Node.js 20"
      - docker pull node:20-alpine
  build:
    commands:
      - docker run --rm -v $PWD:/app -w /app public.ecr.aws/docker/library/node:20-alpine sh -c "npm ci && npm run build"
      - test -d dist && echo "dist directory found" || echo "dist directory not found"
  post_build:
    commands:
      - echo "Verifying appspec.yml exists"
      - ls -la appspec.yml
      - echo "Creating zip archive"
      - zip -r app.zip . -x ".git/*" "node_modules/*"
      - echo "Verifying zip contents"
      - unzip -l app.zip | head -20
      - echo "Uploading zip to S3"
      - aws s3 cp app.zip s3://codepipeline-dentalweb/app.zip
      - echo "Deployment completed"
artifacts:
  files:
    - app.zip
