version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
  pre_build:
    commands:
      - echo "Checking package.json scripts..."
      - cat package.json | grep -A 10 '"scripts"'
  build:
    commands:
      - echo "Running build..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
