version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://fnm.vercel.app/install | bash
      - export PATH="$HOME/.local/share/fnm:$PATH"
      - eval "$(fnm env)"
      - fnm install 20
      - fnm use 20
      - node --version
      - npm ci
  build:
    commands:
      - export PATH="$HOME/.local/share/fnm:$PATH"
      - eval "$(fnm env)"
      - fnm use 20
      - npm run build
      - test -d dist && echo "dist directory found" || echo "dist directory not found"
artifacts:
  files:
    - '**/*'
