version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Specify your project's Node.js version
    commands:
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running build script..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build' # Or 'dist', 'out', etc., depending on your build output folder
