version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 20..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - node --version
      - npm --version
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "Running Astro build..."
      - npm run build
      - echo "Build completed, checking output:"
      - test -d dist && echo "dist directory found" || echo "dist directory not found"
artifacts:
  files:
    - '**/*'
