version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - node -v 
  build:
    commands:
      - echo "Running Astro build..."
      - npm run build
      - echo "Build completed, checking output:"
      - pwd
      - ls -la
      - echo "Looking for build output:"
      - find . -maxdepth 2 -type d
      - echo "Checking if dist exists:"
      - test -d dist && echo "dist directory found" || echo "dist directory not found"
artifacts:
  files:
    - '**/*'
