version: 0.2

phases:
  pre_build:
    commands:
      - echo "Using Docker to run Node.js 20"
      - docker pull node:20-alpine
  build:
    commands:
      - docker run --rm -v $PWD:/app -w /app node:20-alpine sh -c "npm ci && npm run build"
      - test -d dist && echo "dist directory found" || echo "dist directory not found"
  post_build:
    commands:
      - echo "Deploying entire repo to S3"
      - aws s3 sync . s3://codepipeline-dentalweb/ --delete --exclude ".git/*"
      - echo "Deployment completed"
artifacts:
  files:
    - '**/*'
